# Generated by Django 5.2.3 on 2025-07-01 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
