# Generated by Django 5.2.3 on 2025-07-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_date_posted_blog_created_at_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Travel', 'Travel'), ('Education', 'Education'), ('Health', 'Health'), ('AI', 'AI')], default='Technology', max_length=20),
            preserve_default=False,
        ),
    ]
