# Generated by Django 5.2.3 on 2025-07-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_type_blog_author_blog_top_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='top',
        ),
    ]
