# Generated by Django 5.2.3 on 2025-07-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addBlogs', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='addblog',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
